### ISSUE TITLE
delimiter "space" not working

### ISSUE THREAD

**Issue by temp3r** [xoxco/jQuery-Tags-Input#231]
```javascript
$('.zip').tagsInput({
'delimiter': [',',';',' ']
});
```

Tried the above, and comma and tab work, just not space
How to make space a delimiter?

**Comment by lucknerjb** [comment]
The option to pass in an array of delimiters was reverted in 7a050e1940c5ae02a7e252803c77d40e4e5bb483 due to this being a v2 option (v2 comes out in a few weeks).

For the time being, you could hack the functionality with something like this:

```
var triggerEnter = function(elem) {
   var e = jQuery.Event("keypress");
   e.which = 13; //choose the one you want
   e.keyCode = 13;
   elem.trigger(e);
};

$(document).bind('keypress', '#tags_1', function(e) {
   if (e.which === 32) {
      triggerEnter($(e.target));
   }
});
```

By triggering the Enter key, you force the contents of the input to be added as a tag. Hope this helps for the time being!!

**Comment by lucknerjb** [comment]
Closing ticket, please re-open / comment if need be.
